# Generated by Django 6.0.3 on 2026-04-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='Entreprise / Organisation')),
                ('service', models.CharField(blank=True, choices=[('branding', 'Branding & Identité visuelle'), ('digital', 'Marketing Digital'), ('evenement', 'Événementiel'), ('print', 'Print & Édition'), ('social', 'Social Media & Community'), ('audiovisuel', 'Audiovisuel & Production'), ('conseil', 'Conseil Stratégique'), ('autre', 'Autre')], max_length=30, verbose_name='Service souhaité')),
                ('message', models.TextField(verbose_name='Message')),
                ('lang', models.CharField(default='fr', max_length=5, verbose_name='Langue')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Répondu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
